version: "3.8"
services:
  mongo_db: 
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  backend:
    build: ./Backend
    container_name: backend
    ports: 
      - 8000:8000
    volumes:
      - ./Backend:/app
      # - ./app/node_modules
    environment:
      port: 8000
      dbUrl: 'mongodb://mongo_db:27017/hospital' 
      key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
    depends_on:
      - mongo_db
    
  frontend:
    build: ./FrontEnd
    container_name: frontend
    ports: 
      - 3000:3000
    volumes:
      - ./FrontEnd:/app
      # - ./app/node_modules
    stdin_open: true
    tty: true
volumes:
  mongo_db: {}